language: python
cache: pip

matrix:
  fast_finish: true
  include:
    - python: pypy3
    - python: 2.7
    - python: 3.5
    - python: 3.6
    - python: 3.7
      dist: xenial
    - python: 3.8-dev
      dist: xenial

install:
 - pip install pillow
 - pip install coveralls

script:
 - coverage run --source=piexif setup.py test

after_success:
  coveralls
