build: false

environment:
  matrix:
  - PYTHON: C:/Python37-x64
  - PYTHON: C:/Python35-x64
  - PYTHON: C:/Python27-x64

install:
  - "%PYTHON%/python.exe -m pip install pillow"

test_script:
  - '%PYTHON%/python.exe setup.py test'
